# Nome da aplicação
spring.application.name=agenda-cdb

# Configuração da Porta para o Render (Ele injeta a variável PORT, se não achar usa 8080 local)
server.port=${PORT:8080}

# Configuração do Banco de Dados (Pronto para o Render e Local)
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/barbearia_db}
spring.datasource.username=${DB_USER:postgres}
spring.datasource.password=${DB_PASSWORD:admin}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Chave secreta para o Token JWT
api.security.token.secret=${JWT_SECRET:minha-chave-secreta-ultra-mega-segura-123}

# Configuração de fuso horário (Brasil)
spring.jackson.time-zone=America/Sao_Paulo

# Dados do Administrador Padrão (Seeder)
admin.default.nome=${ADMIN_NOME:Alef Amaral}
admin.default.cpf=${ADMIN_CPF:07934307632}
admin.default.whatsapp=${ADMIN_WHATSAPP:33999026412}
admin.default.senha=${ADMIN_SENHA:Afra-1993}

# Configuração de CORS (URLs permitidas para acessar a API)
cors.allowed-origins=${CORS_ORIGINS:https://agenda-cdb.onrender.com,http://localhost:5500,http://127.0.0.1:5500}